### ISSUE TITLE
Cancellation doesn't work in 32-bit iOS 9 simulator

### ISSUE THREAD

**Issue by lilyball** [kballard/Tomorrowland#19]
Running the test suite in a 32-bit iOS 9 simulator results in a lot of test failures for tests on cancellation behavior. I'm unsure why this is at the moment.

**Comment by kballard** [comment]
Looks like it's strictly tests for cancellation propagation, and even there, it's only Obj-C tests, not Swift tests.

**Comment by kballard** [comment]
Turns out cancellation propagation works perfectly fine, I just need to add autorelease pools to the tests.

**Comment by kballard** [comment]
I don't know why the objects are getting autoreleased at all though ¯\_(ツ)_/¯
