### ISSUE TITLE
not an issue - but want to ask question - one liner

### ISSUE THREAD

**Issue by wweevv-johndpope** [kballard/Tomorrowland#61]
<img width="542" alt="Screen Shot 2022-09-01 at 10 44 03 pm" src="https://user-images.githubusercontent.com/109928647/187916717-74685e8c-bec2-4e2b-ad51-28e8aa844cb2.png">

<img width="960" alt="Screen Shot 2022-09-01 at 10 42 53 pm" src="https://user-images.githubusercontent.com/109928647/187916740-e2026488-1030-47c9-9e57-83297f65ac4f.png">

https://github.com/wweevv-johndpope/Telegram-iOS/tree/ios13

MTDisposable.m
 class is ridled with out of date methods. how can I translate this line?

`objective-c
 if (OSAtomicCompareAndSwapPtr(block, 0, &_block))
`

https://github.com/crossroadvn/ext-2017-net.wrappy.OldMtProtoKit-fe-iOS/blob/3eafcc2d9c0b6563abdba9fad5d46720ddc41c1e/MTDisposable.m

**Comment by wweevv-johndpope** [comment]
(maybe this library could be switched in for this ?

**Comment by wweevv-johndpope** [comment]
found this - https://stackoverflow.com/questions/12384050/using-osatomiccompareandswapptr-on-ios-with-arc-enabled/73574395#73574395

**Comment by lilyball** [comment]
@wweevv-johndpope Hello! I'm glad you figured out a solution, although I'm going to leave a few comments on your commit
